### DISCUSSION TITLE
socket.io failed connections when testing with Artillery

### DISCUSSION THREAD

**Discussion by DouglasLapsley** [socketio/socket.io#4341] [Q&A] [answered]
I'm setting up a node.js socket.io server and need to support around 10k users.  [This guide][1] says it should be possible to get up to 55k concurrent connections.

I'm hosting on an Ubuntu 20.04 EC2 with 4 vcpus and 16b RAM.  Socket.io JavaScript (reduced for clarity) for node.js is:

    import * as express from "express";
    import { createServer } from "http";
    import * as fs from 'fs';
    import * as https from 'https';
    import * as path from 'path';
    import { Server } from "socket.io";
    import * as os from 'os';
    import * as sticky from 'sticky-session'; // Required to make use of multiple processors

    let httpServer;
    const app = express();

    port = 443;

    // Certificate
    const privateKey = fs.readFileSync('MYPATH/privkey.pem', 'utf8');
    const certificate = fs.readFileSync('MYPATH/cert.pem', 'utf8');
    const ca = fs.readFileSync('MYPATH/chain.pem', 'utf8');

    const credentials = {
      key: privateKey,
      cert: certificate,
      ca: ca
    };

    httpServer = https.createServer(credentials, app);

    const io = new Server(httpServer, {
      cors: {
        origin: [
          MYORIGINS
        ]
      }
    });

    io.on('connection', (socket) => {
      // MY ENDPOINTS
    });

    if (!sticky.listen(httpServer, port)) {
      // Master code
      httpServer.once('listening', function() {
        console.log('server started on port port');
      });
    } else {
      // Worker code
    }

I've followed the steps in the guide above doing:

`sudo nano /etc/security/limits.d/custom.conf` and adding the following lines:

    * soft nofile 1048576
    * hard nofile 1048576

And `sudo nano /etc/sysctl.d/net.ipv4.ip_local_port_range.conf` adding:

    net.ipv4.ip_local_port_range = 10000 65535

I've also read through and tried the settings from [this article][2].

I am testing with Artillery with the following YAML config:

    config:
      target: "MYURL"
      phases:
        - duration: 20
          arrivalRate: 250
      engines:
       socketio-v3: {
         transports: ["websocket"]
       }

    scenarios:
      - name: My load testing
        engine: socketio-v3
        flow:
          - think: 20

I am getting really varied results.  With exactly those settings I am getting 0 `vusers.failed` which is good, but that only gives me 5000 users.

If I increase either the duration or the arrival rate to give a higher overall number of users I start to get significant numbers of `vusers.failed`.  e.g. Creating 20k users I get 9k failed. Creating 50k users I get 49k failed!

I'm not quite sure exactly what `vusers.failed` means (I couldn't find documentation).

I'm using `sticky-session` on advice from [this article][2] as I want all 4 CPU cores to be used.  That seems to run 4x instances of the httpServer.  I am not 100% sure if this is needed as I am never seeing CPU use go above 20% or so however hard I hit it with users.

What does `vusers.failed` mean exactly?

Why am I getting `vusers.failed` errors like this?

What do I need to change?

Do I need the sticky sessions and is that what's required to use all 4 processor cores on the server?

Thanks very much!

  [1]: https://socket.io/docs/v4/performance-tuning/
  [2]: https://blog.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/

**Comment by darrachequesne** [comment, marked as answer]
Hi!

- which version of artillery are you using? It seems there was a lot of updates recently. Does it run in multi-threaded mode?

- did you try with [manual client creation](https://socket.io/docs/v4/load-testing/#manual-client-creation)?

- which `arrivalRate` are you using? Sometimes a high `arrivalRate` can lead to issues from artillery.

I was able to happily go to 25k clients without any problem on my machine with one single Socket.IO server (`artillery@1.7.9`):

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 480
      arrivalRate: 200
```

Result:

```
All virtual users finished
Summary report
  Scenarios launched:  96000
  Scenarios completed: 96000
  Requests completed:  0
  Mean response/sec: NaN
  Response time (msec):
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    My load testing: 96000 (100%)
```

Please note that sticky sessions are not needed if you are only using WebSockets. In that case, using `sticky-session` will make it worse, because it load balances the incoming connections based on the IP address, so every connection will end up on a single node.

If you also need HTTP long-polling, please check the `@socket.io/sticky` module: https://socket.io/docs/v4/using-multiple-nodes/#using-nodejs-cluster

**Reply by DouglasLapsley** [reply]
Thanks for getting back to me on this.  I'm using `"artillery": "^2.0.0-14"` and `"artillery-engine-socketio-v3": "^1.1.2"` and my socket.io app is using `"socket.io": "^4.4.1"`.

Apparently Artillery 2> has [support for multi-threading out of the box](https://www.artillery.io/docs/resources/core/v2-migration-guide#multithreading).

I had tried with arrival rates of between 50 - 250.  Results were consistent.

I've now removed the `sticky-session` and forced socket.io to run with only the websocket transport:
```
const io = new Server(httpServer, {
  cors: {
    origin: [
     MYORIGINS
    ]
  },
  transports: ['websocket']
});
```

Now I run artillery with the following config:

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 480 
      arrivalRate: 200
  engines:
   socketio-v3: {
     transports: ["websocket"]
   }

scenarios:
  - name: My load testing
    engine: socketio-v3
    flow:
      - think: 100

```

**Locally** I get:
```
vusers.completed: .............................................................. 96000
vusers.created: ................................................................ 96000
vusers.created_by_name.My load testing: ........................................ 96000
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 100000.1
  max: ......................................................................... 101612.4
  median: ...................................................................... 99741.2
  p95: ......................................................................... 99741.2
  p99: ......................................................................... 101756.1
```

Woohoo!

However, when I run the same test against the same code on the web server I get the following.  To be clear I am running Artillery on my local machine, hitting the remote web server:
```
errors.Error: websocket error: ................................................. 95997
vusers.completed: .............................................................. 3
vusers.created: ................................................................ 96000
vusers.created_by_name.My load testing: ........................................ 96000
vusers.failed: ................................................................. 95997
vusers.session_length:
  min: ......................................................................... 100127
  max: ......................................................................... 100155.8
  median: ...................................................................... 99741.2
  p95: ......................................................................... 99741.2
  p99: ......................................................................... 99741.2
```
So there is clearly something about the config on the server or the way Artillery is calling that is causing this failure (or an issue between my local machine and remote - 70Mbps broadband though so...).  Local machine is Ubuntu 20.04 and server is Ubuntu Server 20.04.

When I ran the [manual client creation](https://socket.io/docs/v4/load-testing/#manual-client-creation) script without any emits (so as just to count the client connections) and running in `websocket` mode I was able to get up to 48k clients before things slowed down and `disconnect due to ping timeout`, so it looks like it's maybe Artillery.

**Will the server use more than one virtual CPU if sticky sessions are not enabled?**  I'm not sure how node.js and socket.io distribute processes and can only find information about horizontal scaling with Redis etc.  And the CPU never seems to go more than 20% on any one CPU core even when I've sending a lot of requests at it.
