### DISCUSSION TITLE
Socket.io Client Not Connecting to AKS-Deployed Socket.io Server (Only Receiving 40 Without sid)

### DISCUSSION THREAD

**Discussion by raghu-gade** [socketio/socket.io#5314] [Q&A]
I’m facing an issue where my Socket.io client fails to fully connect to a Socket.io server deployed on AKS.
- When running Socket.io locally, the client correctly receives the 40{"sid":"<socket_id>"} message, meaning the connection is successful.
     <img width="463" alt="image" src="https://github.com/user-attachments/assets/300dcc9a-433b-4c8b-b020-7439e9e80b52" />
- When connecting to the AKS-deployed server, the client only receives 40 without the sid, and the connection does not complete.
     <img width="466" alt="image" src="https://github.com/user-attachments/assets/5f05a5b0-cd26-4fad-9aed-5996aee8c38c" />
- The issue happens over wss://, but the same client works fine when connecting to a local server.

**Server**: Node.js with Socket.io (`socket.io@4.7.5`)
```
io.on("connection", (socket) => {
        console.log("Socket connected:", socket.id);
      });
```
**Client**: Angularapp (`socket.io-client@4.7.5`)
```
 this.socket = io("https://myapplication.com",
      {
      transports: ["websocket"],
       path: "/nodeapp/socket.io/"
      });
      this.socket.on("connect", (socketdata:any) => {
      console.log("Connected to server");
      });
```
**Deployment**: AKS with NGINX Ingress Ingress Annotations:
```
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/error-log-level: "debug"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600" 
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
   - host: 
     paths:
       - path: /nodeapp(/|$)(.*)
         pathType: ImplementationSpecific
```
Why does the Socket.io client only receive 40 (without sid) when connecting via Ingress?

Could this be an issue with Ingress proxy headers stripping the sid? Any known Azure or NGINX settings that affect WebSocket handshake completion? Would appreciate any insights or troubleshooting tips! Someone confirms a known issue with Socket.io, NGINX Ingress and suggests a fix.
