### ISSUE TITLE
Getting HTTP error 400

### ISSUE THREAD

**Issue by moxpatwa** [socketio/socket.io#4881]
Hello,

I am getting HTTP Error 400 around.

I am using socket-io 4.7.2 and socket-io-client 4.7.2 and I am using react for front end this is my client side settings
<img width="834" alt="Test png" src="https://github.com/socketio/socket.io-client/assets/64414384/15aadc73-174b-42c6-a673-9e858212923d">

in server side using node is which setting describe below:
![Test02 png](https://github.com/socketio/socket.io-client/assets/64414384/5e404092-5664-4ea5-b68a-34a1a9b06c22)

Can you suggest me solutions for that?

_Originally posted by @moxpatwa in https://github.com/socketio/socket.io-client/issues/1474#issuecomment-1828424530_

**Comment by moxpatwa** [comment]
Any update on above issue

**Comment by moxpatwa** [comment]
@dshaw any update on above issue.

**Comment by darrachequesne** [comment]
Hi! HTTP 400 status usually means sticky sessions are not enabled properly, could you please check?

Reference: https://socket.io/docs/v4/using-multiple-nodes/

**Comment by moxpatwa** [comment]
Thanks @darrachequesne .. i will try enable sticky session and let you if i still facing same issue or not.

**Comment by moxpatwa** [comment]
@darrachequesne I am using node.js for service and react for frontend.. to enable sticky connection can you suggenst me best approach as our nodejs service container some rest endpoint ,scheduler, socketio.

**Comment by fillipearaujo** [comment]
For those who are having trouble with sticky session polling on a Kubernetes server. Below is an example of annotations declaration in ingress.yaml to enable the sticky session.

Status: 400
Error: {"code":1,"message":"Session ID unknown"}

```
   annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "route"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
```
